#include "parser.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
static char*fmt(const char*f,...){va_list a,b;va_start(a,f);va_copy(b,a);int n=vsnprintf(NULL,0,f,a);va_end(a);char*s=malloc(n+1);vsnprintf(s,n+1,f,b);va_end(b);return s;}
static Token*cur(Parser*p){return &p->toks.v[p->p];} static int is(Parser*p,TokenType t){return cur(p)->tipo==t;} static Token adv(Parser*p){Token t=*cur(p);if(p->p+1<p->toks.n)p->p++;return t;}
static void fail(Parser*p,const char*m){if(!p->erro){Token*t=cur(p);p->erro=fmt("%s, encontrado %s ('%s') na linha %d, coluna %d",m,token_nome(t->tipo),t->lexema,t->linha,t->coluna);}}
static Token take(Parser*p,TokenType t){if(!is(p,t)){char b[80];snprintf(b,sizeof b,"esperado %s",token_nome(t));fail(p,b);return *cur(p);}return adv(p);}
static int type_tok(TokenType t){return t==T_INT||t==T_FLOAT||t==T_BOOL||t==T_CHAR||t==T_VOID;}
static void mark(Parser*p,No*n,int l,int c){if(!n||p->p==0)return;Token*t=&p->toks.v[p->p-1];n->linha=l;n->coluna=c;n->fim_linha=t->linha;n->fim_coluna=t->coluna+(int)strlen(t->lexema);n->tem_fim=1;}
static No*expr(Parser*p);static No*command(Parser*p);static No*block(Parser*p);
static No*primary(Parser*p){Token t=*cur(p);if(is(p,T_IDENT)){adv(p);No*n=no_novo(N_IDENT,t.linha,t.coluna);n->u.ident.nome=strdup(t.lexema);mark(p,n,t.linha,t.coluna);return n;}if(t.tipo==T_INT_LIT||t.tipo==T_FLOAT_LIT||t.tipo==T_TRUE||t.tipo==T_FALSE||t.tipo==T_STRING_LIT||t.tipo==T_CHAR_LIT){adv(p);No*n=no_novo(N_LITERAL,t.linha,t.coluna);n->u.literal.lexema=strdup(t.lexema);if(t.tipo==T_INT_LIT){n->u.literal.tipo_literal=L_INT;n->u.literal.valor_int=t.ival;}else if(t.tipo==T_FLOAT_LIT){n->u.literal.tipo_literal=L_REAL;n->u.literal.valor_real=t.fval;}else if(t.tipo==T_TRUE||t.tipo==T_FALSE){n->u.literal.tipo_literal=L_BOOL;n->u.literal.valor_bool=(t.tipo==T_TRUE);}else if(t.tipo==T_CHAR_LIT)n->u.literal.tipo_literal=L_CHAR;else n->u.literal.tipo_literal=L_STRING;mark(p,n,t.linha,t.coluna);return n;}if(is(p,T_LPAREN)){adv(p);No*n=expr(p);take(p,T_RPAREN);if(n)mark(p,n,t.linha,t.coluna);return n;}fail(p,"esperado identificador, literal ou '('");return NULL;}
static No*postfix(Parser*p){No*n=primary(p);while(!p->erro){if(is(p,T_LPAREN)){Token t=adv(p);No*x=no_novo(N_CHAMADA,t.linha,t.coluna);x->u.chamada.funcao=n;if(!is(p,T_RPAREN)){novec_push(&x->u.chamada.argumentos,expr(p));while(is(p,T_COMMA)){adv(p);novec_push(&x->u.chamada.argumentos,expr(p));}}take(p,T_RPAREN);x->linha=n->linha;x->coluna=n->coluna;mark(p,x,n->linha,n->coluna);n=x;}else if(is(p,T_LBRACKET)){Token t=adv(p);No*x=no_novo(N_INDICE,t.linha,t.coluna);x->u.indice.vetor=n;x->u.indice.indice=NULL;if(!p->erro)x->u.indice.indice=expr(p);take(p,T_RBRACKET);x->linha=n->linha;x->coluna=n->coluna;mark(p,x,n->linha,n->coluna);n=x;}else break;}return n;}
static No*unary(Parser*p){if(is(p,T_MINUS)||is(p,T_NOT)){Token t=adv(p);No*n=no_novo(N_UNARIA,t.linha,t.coluna);n->u.un.operador=strdup(t.lexema);n->u.un.operando=unary(p);mark(p,n,t.linha,t.coluna);return n;}return postfix(p);}
static No*leftbin(Parser*p,No*(*sub)(Parser*),int nops,...){No*n=sub(p);while(!p->erro){TokenType tt=is(p,T_OR)?T_OR:cur(p)->tipo;int ok=0;va_list ap;va_start(ap,nops);for(int i=0;i<nops;i++)if(tt==va_arg(ap,int))ok=1;va_end(ap);if(!ok)break;Token t=adv(p);No*x=no_novo(N_BINARIA,n->linha,n->coluna);x->u.bin.operador=strdup(t.lexema);x->u.bin.esquerda=n;x->u.bin.direita=sub(p);mark(p,x,n->linha,n->coluna);n=x;}return n;}
static No*mul(Parser*p){return leftbin(p,unary,3,T_STAR,T_SLASH,T_PERCENT);}static No*add(Parser*p){return leftbin(p,mul,2,T_PLUS,T_MINUS);}static No*rel(Parser*p){return leftbin(p,add,4,T_LT,T_GT,T_LE,T_GE);}static No*eq(Parser*p){return leftbin(p,rel,2,T_EQ,T_NE);}static No*land(Parser*p){return leftbin(p,eq,1,T_AND);}static No*lor(Parser*p){return leftbin(p,land,1,T_OR);}
static No*expr(Parser*p){No*l=lor(p);if(is(p,T_ASSIGN)){if(p->estrito&&!(l&& (l->kind==N_IDENT||l->kind==N_INDICE))){fail(p,"alvo de atribuição inválido");return l;}Token t=adv(p);No*n=no_novo(N_ATRIB,l?l->linha:t.linha,l?l->coluna:t.coluna);n->u.atrib.alvo=l;n->u.atrib.valor=expr(p);mark(p,n,n->linha,n->coluna);return n;}return l;}
static No*param(Parser*p){Token ty=adv(p);Token nm=take(p,T_IDENT);No*n=no_novo(N_PARAMETRO,nm.linha,nm.coluna);n->u.parametro.tipo_base=strdup(ty.lexema);n->u.parametro.nome=strdup(nm.lexema);if(is(p,T_LBRACKET)){adv(p);take(p,T_RBRACKET);n->u.parametro.eh_vetor=1;}return n;}
static No*decl_rest(Parser*p,Token ty,Token nm){No*d=no_novo(N_DECLVAR,nm.linha,nm.coluna);d->u.declvar.tipo_base=strdup(ty.lexema);d->u.declvar.nome=strdup(nm.lexema);if(is(p,T_LBRACKET)){adv(p);d->u.declvar.tamanho=expr(p);take(p,T_RBRACKET);}if(is(p,T_ASSIGN)){adv(p);d->u.declvar.inicializador=expr(p);}return d;}
static No*decl(Parser*p){Token ty=adv(p);Token nm=take(p,T_IDENT);if(is(p,T_LPAREN)){adv(p);No*f=no_novo(N_FUNCAO,ty.linha,ty.coluna);f->u.funcao.tipo_retorno=strdup(ty.lexema);f->u.funcao.nome=strdup(nm.lexema);f->u.funcao.linha_nome=nm.linha;f->u.funcao.coluna_nome=nm.coluna;if(!is(p,T_RPAREN)){novec_push(&f->u.funcao.parametros,param(p));while(is(p,T_COMMA)){adv(p);novec_push(&f->u.funcao.parametros,param(p));}}take(p,T_RPAREN);f->u.funcao.corpo=block(p);return f;}No*first=decl_rest(p,ty,nm);No*res=first;NoVec list={0};novec_push(&list,first);while(is(p,T_COMMA)){adv(p);Token x=take(p,T_IDENT);novec_push(&list,decl_rest(p,ty,x));}take(p,T_SEMICOLON);if(list.n>1){No*l=no_novo(N_LISTADECL,ty.linha,ty.coluna);l->u.listadecl.declaracoes=list;res=l;}else free(list.v);return res;}
static No*block(Parser*p){Token t=take(p,T_LBRACE);No*b=no_novo(N_BLOCO,t.linha,t.coluna);while(!is(p,T_RBRACE)&&!is(p,T_EOF)){novec_push(&b->u.bloco.comandos,command(p));if(p->erro)break;}take(p,T_RBRACE);return b;}
static No*command(Parser*p){if(type_tok(cur(p)->tipo))return decl(p);if(is(p,T_IF)){Token t=adv(p);take(p,T_LPAREN);No*c=expr(p);take(p,T_RPAREN);No*n=no_novo(N_IF,t.linha,t.coluna);n->u.ifn.condicao=c;n->u.ifn.entao=command(p);if(is(p,T_ELSE)){adv(p);n->u.ifn.senao=command(p);}return n;}if(is(p,T_WHILE)){Token t=adv(p);take(p,T_LPAREN);No*c=expr(p);take(p,T_RPAREN);No*n=no_novo(N_WHILE,t.linha,t.coluna);n->u.whilen.condicao=c;n->u.whilen.corpo=command(p);return n;}if(is(p,T_FOR)){Token t=adv(p);take(p,T_LPAREN);No*n=no_novo(N_FOR,t.linha,t.coluna);n->u.forn.inicio=is(p,T_SEMICOLON)?NULL:expr(p);take(p,T_SEMICOLON);n->u.forn.condicao=is(p,T_SEMICOLON)?NULL:expr(p);take(p,T_SEMICOLON);n->u.forn.passo=is(p,T_RPAREN)?NULL:expr(p);take(p,T_RPAREN);n->u.forn.corpo=command(p);return n;}if(is(p,T_RETURN)){Token t=adv(p);No*n=no_novo(N_RETURN,t.linha,t.coluna);n->u.ret.expressao=is(p,T_SEMICOLON)?NULL:expr(p);take(p,T_SEMICOLON);return n;}if(is(p,T_BREAK)){Token t=adv(p);take(p,T_SEMICOLON);return no_novo(N_BREAK,t.linha,t.coluna);}if(is(p,T_CONTINUE)){Token t=adv(p);take(p,T_SEMICOLON);return no_novo(N_CONTINUE,t.linha,t.coluna);}if(is(p,T_PRINT)){Token t=adv(p);take(p,T_LPAREN);No*n=no_novo(N_PRINT,t.linha,t.coluna);n->u.printn.argumento=expr(p);take(p,T_RPAREN);take(p,T_SEMICOLON);return n;}if(is(p,T_READ)){Token t=adv(p);take(p,T_LPAREN);No*n=no_novo(N_READ,t.linha,t.coluna);n->u.readn.alvo=expr(p);if(p->estrito&&n->u.readn.alvo&&n->u.readn.alvo->kind!=N_IDENT&&n->u.readn.alvo->kind!=N_INDICE)fail(p,"read exige uma variável ou posição de vetor");take(p,T_RPAREN);take(p,T_SEMICOLON);return n;}if(is(p,T_LBRACE))return block(p);Token t=*cur(p);No*n=no_novo(N_EXPRSTMT,t.linha,t.coluna);if(is(p,T_SEMICOLON)){adv(p);return n;}n->u.exprstmt.expressao=expr(p);take(p,T_SEMICOLON);return n;}
int parser_init(Parser*p,const char*fonte,int estrito){memset(p,0,sizeof(*p));p->fonte=fonte;p->estrito=estrito;return scanner_ler(fonte,&p->toks);}
No*analisar_sintaxe(Parser*p){No*n=no_novo(N_PROGRAMA,cur(p)->linha,cur(p)->coluna);while(!is(p,T_EOF)&&!p->erro){if(type_tok(cur(p)->tipo))novec_push(&n->u.programa.declaracoes,decl(p));else novec_push(&n->u.programa.declaracoes,command(p));}if(p->erro){no_free(n);return NULL;}return n;}
void parser_free(Parser*p){tokens_free(&p->toks);free(p->erro);p->erro=NULL;}
