#include "scanner.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static char* dupn(const char*s,size_t n){char*p=malloc(n+1);if(!p)exit(1);memcpy(p,s,n);p[n]=0;return p;}
static void push(TokenVec*v,Token t){if(v->n==v->cap){v->cap=v->cap?v->cap*2:64;v->v=realloc(v->v,v->cap*sizeof(Token));if(!v->v)exit(1);}v->v[v->n++]=t;}
static void err(TokenVec*v,const char*msg,int l,int c,const char*s,size_t n){v->erro=1;v->erro_msg=malloc(strlen(msg)+n+64);sprintf(v->erro_msg,"%s ('%.*s') na linha %d, coluna %d",msg,(int)n,s,l,c);v->erro_linha=l;v->erro_coluna=c;}
static int kw(const char*s,TokenType*t){struct K{const char*n;TokenType t;}k[]={ {"int",T_INT},{"float",T_FLOAT},{"bool",T_BOOL},{"char",T_CHAR},{"void",T_VOID},{"if",T_IF},{"else",T_ELSE},{"while",T_WHILE},{"for",T_FOR},{"return",T_RETURN},{"break",T_BREAK},{"continue",T_CONTINUE},{"true",T_TRUE},{"false",T_FALSE},{"print",T_PRINT},{"read",T_READ}};for(size_t i=0;i<sizeof(k)/sizeof(k[0]);i++)if(!strcmp(s,k[i].n)){*t=k[i].t;return 1;}return 0;}
const char*token_nome(TokenType t){static const char*n[]={"INT","FLOAT","BOOL","CHAR","VOID","IF","ELSE","WHILE","FOR","RETURN","BREAK","CONTINUE","TRUE","FALSE","PRINT","READ","IDENT","FLOAT_LIT","INT_LIT","STRING_LIT","CHAR_LIT","EQ","NE","LE","GE","AND","OR","PLUS","MINUS","STAR","SLASH","PERCENT","LT","GT","NOT","ASSIGN","LPAREN","RPAREN","LBRACE","RBRACE","LBRACKET","RBRACKET","SEMICOLON","COMMA","DOT","EOF"};return n[t];}
void tokens_free(TokenVec*v){for(size_t i=0;i<v->n;i++)free(v->v[i].lexema);free(v->v);free(v->erro_msg);memset(v,0,sizeof(*v));}
int scanner_ler(const char*s,TokenVec*out){memset(out,0,sizeof(*out));size_t i=0;int l=1,c=1;while(s[i]){char ch=s[i];if(isspace((unsigned char)ch)){if(ch=='\n'){l++;c=1;}else c++;i++;continue;}int sl=l,sc=c;
if(ch=='/'&&s[i+1]=='/'){i+=2;c+=2;while(s[i]&&s[i]!='\n'){i++;c++;}continue;}if(ch=='/'&&s[i+1]=='*'){i+=2;c+=2;int ok=0;while(s[i]){if(s[i]=='*'&&s[i+1]=='/'){i+=2;c+=2;ok=1;break;}if(s[i]=='\n'){i++;l++;c=1;}else{i++;c++;}}if(!ok){err(out,"UNTERMINATED_BLOCK_COMMENT",sl,sc,s+(i?i-1:0),1);return 0;}continue;}
if(ch=='"'||ch=='\''){char q=ch;size_t st=i;i++;c++;int ok=0;while(s[i]){if(s[i]==q){i++;c++;ok=1;break;}if(s[i]=='\n')break;if(s[i]=='\\'&&s[i+1]){i+=2;c+=2;}else{i++;c++;}}if(!ok){err(out,q=='"'?"UNTERMINATED_STRING":"UNTERMINATED_CHAR",sl,sc,s+st,i-st);return 0;}size_t len=i-st;Token t={q=='"'?T_STRING_LIT:T_CHAR_LIT,dupn(s+st,len),sl,sc};if(q=='"')t.ival=0;push(out,t);continue;}
if(isalpha((unsigned char)ch)||ch=='_'){size_t st=i;while(isalnum((unsigned char)s[i])||s[i]=='_'){i++;c++;}char*x=dupn(s+st,i-st);TokenType tt=T_IDENT;kw(x,&tt);push(out,(Token){tt,x,sl,sc});continue;}
if(isdigit((unsigned char)ch)){size_t st=i;while(isdigit((unsigned char)s[i])){i++;c++;}TokenType tt=T_INT_LIT;if(s[i]=='.'&&isdigit((unsigned char)s[i+1])){tt=T_FLOAT_LIT;i++;c++;while(isdigit((unsigned char)s[i])){i++;c++;}}char*x=dupn(s+st,i-st);Token t={tt,x,sl,sc};if(tt==T_INT_LIT)t.ival=strtoll(x,0,10);else t.fval=strtod(x,0);push(out,t);continue;}
TokenType tt=0;size_t len=1;if((ch=='='&&s[i+1]=='=')||(ch=='!'&&s[i+1]=='=')||(ch=='<'&&s[i+1]=='=')||(ch=='>'&&s[i+1]=='=')||(ch=='&'&&s[i+1]=='&')||(ch=='|'&&s[i+1]=='|')){if(ch=='=')tt=T_EQ;else if(ch=='!')tt=T_NE;else if(ch=='<')tt=T_LE;else if(ch=='>')tt=T_GE;else if(ch=='&')tt=T_AND;else tt=T_OR;len=2;}else switch(ch){case '+':tt=T_PLUS;break;case '-':tt=T_MINUS;break;case '*':tt=T_STAR;break;case '/':tt=T_SLASH;break;case '%':tt=T_PERCENT;break;case '<':tt=T_LT;break;case '>':tt=T_GT;break;case '!':tt=T_NOT;break;case '=':tt=T_ASSIGN;break;case '(':tt=T_LPAREN;break;case ')':tt=T_RPAREN;break;case '{':tt=T_LBRACE;break;case '}':tt=T_RBRACE;break;case '[':tt=T_LBRACKET;break;case ']':tt=T_RBRACKET;break;case ';':tt=T_SEMICOLON;break;case ',':tt=T_COMMA;break;case '.':tt=T_DOT;break;default:err(out,"UNKNOWN_SYMBOL",sl,sc,s+i,1);return 0;}push(out,(Token){tt,dupn(s+i,len),sl,sc});i+=len;c+=len;}
push(out,(Token){T_EOF,dupn("",0),l,c});return 1;}
